### ISSUE TITLE
Orientation Problems

### ISSUE THREAD

**Issue by JonathanCMitchell** [lilanxiao/Rotated_IoU#19]
Are you able to predict the correct orientation? I find cases where my predicted angles are not the same, OR that my width, height, length values are negative. See photo below:

In this case, the predicted corners may not be the same corner number as the ground truth. So width could be length etc

![losses_giou_epoch_791_](https://user-images.githubusercontent.com/13068956/115303264-42fb8900-a118-11eb-828f-5c0ef7ff98de.png)

**Comment by lilanxiao** [comment]
That's how IoU-loss works. It ONLY maximizes the IoU. IoU-loss doesn't match the corners with the same indices.
