### ISSUE TITLE
ModuleNotFoundError: No module named 'sort_vertices' when run python demo

### ISSUE THREAD

**Issue by jasmine202106** [lilanxiao/Rotated_IoU#24]
Please help to check what's wrong with the demo. thanks.

**sudo /home/liey/anaconda3/envs/open-mmlab/bin/python setup.py install**
running install
running bdist_egg
running egg_info
writing sort_vertices.egg-info/PKG-INFO
writing dependency_links to sort_vertices.egg-info/dependency_links.txt
writing top-level names to sort_vertices.egg-info/top_level.txt
reading manifest file 'sort_vertices.egg-info/SOURCES.txt'
writing manifest file 'sort_vertices.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-3.7/sort_vertices.cpython-37m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
creating stub loader for sort_vertices.cpython-37m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/sort_vertices.py to sort_vertices.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying sort_vertices.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sort_vertices.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sort_vertices.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sort_vertices.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
__pycache__.sort_vertices.cpython-37: module references __file__
creating 'dist/sort_vertices-0.0.0-py3.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing sort_vertices-0.0.0-py3.7-linux-x86_64.egg
removing '/home/liey/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/sort_vertices-0.0.0-py3.7-linux-x86_64.egg' (and everything under it)
creating /home/liey/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/sort_vertices-0.0.0-py3.7-linux-x86_64.egg
Extracting sort_vertices-0.0.0-py3.7-linux-x86_64.egg to /home/liey/anaconda3/envs/open-mmlab/lib/python3.7/site-packages
sort-vertices 0.0.0 is already the active version in easy-install.pth

Installed /home/liey/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/sort_vertices-0.0.0-py3.7-linux-x86_64.egg
Processing dependencies for sort-vertices==0.0.0
Finished processing dependencies for sort-vertices==0.0.0

**python demo.py** 
Traceback (most recent call last):
  File "demo.py", line 25, in <module>
    from oriented_iou_loss import cal_diou, cal_giou
  File "/home/liey/3D_multiview/mmdetection3d/mmdet3d/ops/rotated_iou/oriented_iou_loss.py", line 3, in <module>
    from box_intersection_2d import oriented_box_intersection_2d
  File "/home/liey/3D_multiview/mmdetection3d/mmdet3d/ops/rotated_iou/box_intersection_2d.py", line 8, in <module>
    from cuda_op.cuda_ext import sort_v
  File "/home/liey/3D_multiview/mmdetection3d/mmdet3d/ops/rotated_iou/cuda_op/cuda_ext.py", line 4, in <module>
    import sort_vertices
ModuleNotFoundError: No module named 'sort_vertices'

Ubuntu16.04
python3.7.2
torch:1.8.1

**Comment by lilanxiao** [comment]
Hi, it seems the CUDA extension is successfully compiled. However, the python interpreter is not able to call it. 

You've probably used one python interpreter/environment for the `python setup.py install` and use another interpreter for `python demo.py`. I can reproduce the error by using two different Conda environments to compile the code and run the demo, respectively. So please make sure to use the same interpreter. 

BTW, I don't understand why you used SUDO here. It might be irrelevant with this error but it's quite unusual.

**Comment by gireek** [comment]
This issue stays even when only a single Conda environment is used for me. Any suggestions?

**Comment by lilanxiao** [comment]
> This issue stays even when only a single Conda environment is used for me. Any suggestions?

I don't think this issue is caused by my code. 

Probably it's just a problem with the path. Sometimes people get the ModuleNotFoundError, while the module does exist. If it's the case, you only need to add the absolute path of this module to the PYTHONPATH, either by exporting the environment variable directly in the command line or by calling the `sys.path.append` function in the python code before importing the module. 

More info: https://stackoverflow.com/questions/23417941/import-error-no-module-named-does-exist

**Comment by gireek** [comment]
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/35074481/153828288-ad7239dd-8601-4281-a92b-1b488877e95a.png">

The path of sort_vertices shows in the sys.path

**Comment by lilanxiao** [comment]
It seems that the path of my source code is not in the `sys.path`. To use the `sort_vertices` function, we need not only the path under `python3.8/site-packages` but also the source code. Would you please add this at the beginning of the `demo.py` and run it again? 
```
import sys
sys.append(**absolute path of the Rotated_IoU source code**)
```

**Comment by gireek** [comment]
Thanks alot the problem has been solved.
