### ISSUE TITLE
The computational cost of accurate rotated iou?

### ISSUE THREAD

**Issue by colian** [lilanxiao/Rotated_IoU#34]
Thanks for your work.
I notice the computational cost of accurate rotated iou is very high. This code calculates and restores all the situations of intersection, so the GPU memory cost is also very high?

**Comment by lilanxiao** [comment]
yes, my code uses the brute force method. I do so because it's easier to make the brute force method parallelable and differentiable.

**Comment by colian** [comment]
Thanks for your reply, that really helps a lot.
