### ISSUE TITLE
About the 2D coordinates (x, y, w, h, alpha)

### ISSUE THREAD

**Issue by KimSangYeon-DGU** [lilanxiao/Rotated_IoU#42]
Hi, I was curious that the `x, y` means the top left corner of a box.
https://github.com/lilanxiao/Rotated_IoU/blob/3bdca6b20d981dffd773507e97f1b53641e98d0a/oriented_iou_loss.py#L9-L10

I'm asking because it seems some work treats the `x, y` as the center of a box.

**Comment by lilanxiao** [comment]
hi, thank you for the issue. Here `x` and `y` are the coordinates of the box center point. I chose this convention because most object detection methods (e.g. YOLO and R-CNN series) predict the center point instead of the upper left corner.

**Comment by KimSangYeon-DGU** [comment]
Aha, thanks for the clarification :)
